name: Backend CI/CD pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

    workflow_dispatch:

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write permissions
      
jobs:
    Build_and_Push_Image:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./Application-Code/backend
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '14'
    
          - name: Install dependencies
            run: npm install
         
          - name: Set up QEMU on the server
            uses: docker/setup-qemu-action@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            #Docker
          - name: Build and Push
            uses: docker/build-push-action@v5
            with:
              context: ./Application-Code/backend
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_BE }}:${{ github.run_id }}

    update_k8s_deployment_file:
        runs-on: ubuntu-latest
        needs: Build_and_Push_Image
        steps:
          - name: Get Image Tag
            id: tag
            run: echo "tag=${{ github.run_id }}" >> $GITHUB_OUTPUT
              
          - name: Checkout code
            uses: actions/checkout@v3
              
          - name: Set file permissions
            run: chmod 777 Kubernetes/Backend/deployment.yaml
              
          - name: Update Deployment YAML
            run: |
              sed -i "s|image:.*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_BE }}:${{ github.run_id }}|g" Kubernetes/Backendend/deployment.yaml
              cat Kubernetes/Backend/deployment.yaml
            env:
                github_token: ${{ secrets.GH_PAT }}    
          
          - name: Commit changes
            run: |
              git config --global user.email "ci-bot@argocd.com"
              git config --global user.name "ci-bot"
              git add Kubernetes/Backend/deployment.yaml    
              git commit -m "Update image tag"
            env:
              github_token: ${{ secrets.GH_PAT }}
                  
                  #Commit change
          - name: Push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
              github_token: ${{ secrets.GH_PAT }}
              branch: main



